import Local from 'next/font/local';
import Theme from './components/theme';

const material_icons = Local({
    variable: "--material-icons",
    src: [
        {
            path: './assets/icons//MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].woff2',
            weight: '400',
            style: 'normal'
        },
        {
            path: './assets/icons/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].woff2',
            weight: '400',
            style: 'italic'
        },
    ]
});

const roboto = Roboto({
    weight: "400",
    subsets: ['latin']
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
                <Theme>
                <Registry>
                    {children}
                </Registry>
                </Theme>
            </body>
        </html>
    )
}